ToDoList/Models/Tag.cs
using System.Collections.Generic;

namespace ToDoList.Models
{
  public class Tag
    {
        public int TagId { get; set; }
        public string Title { get; set; }
        public List<ItemTag> JoinEntities { get;}
    }
}

ToDoList/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ToDoList.Controllers
{
  public class TagsController : Controller
  {
    private readonly ToDoListContext _db;

    public TagsController(ToDoListContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Tags.ToList());
    }

    public ActionResult Details(int id)
    {
      Tag thisTag = _db.Tags
          .Include(tag => tag.JoinEntities)
          .ThenInclude(join => join.Item)
          .FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      _db.Tags.Add(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddItem(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      ViewBag.ItemId = new SelectList(_db.Items, "ItemId", "Description");
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult AddItem(Tag tag, int itemId)
    {
      #nullable enable
      ItemTag? joinEntity = _db.ItemTags.FirstOrDefault(join => (join.ItemId == itemId && join.TagId == tag.TagId));
      #nullable disable
      if (joinEntity == null && itemId != 0)
      {
        _db.ItemTags.Add(new ItemTag() { ItemId = itemId, TagId = tag.TagId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = tag.TagId });
    }

    public ActionResult Edit(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult Edit(Tag tag)
    {
      _db.Tags.Update(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      return View(thisTag);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      _db.Tags.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      ItemTag joinEntry = _db.ItemTags.FirstOrDefault(entry => entry.ItemTagId == joinId);
      _db.ItemTags.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

ToDoList/Views/Tags/AddItem.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Tag

<h2>Add an item</h2>

<h4>Add an item to this tag: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TagId)

    @Html.Label("Select item")
    @Html.DropDownList("ItemId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Tags/Create.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Tag

<h4>Add a new tag</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Title)
    @Html.TextBoxFor(model => model.Title)

    <input type="submit" value="Add new tag" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all tags", "Index")</p>

ToDoList/Views/Tags/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Tag

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Tags/Details.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models
@model ToDoList.Models.Tag

<h2>Tag Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This tag does not belong to any items</p>
}
else
{
  <h4>Items the tag belongs to:</h4>
  <ul>
  @foreach(ItemTag join in Model.JoinEntities)
  {
    <li>@join.Item.Description</li>
    @using (Html.BeginForm("DeleteJoin", "Tags"))
    {
      @Html.Hidden("joinId", @join.ItemTagId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add an Item", "AddItem", new { id = Model.TagId })</p>
<p>@Html.ActionLink("Edit Tag", "Edit", new { id = Model.TagId })</p>
<p>@Html.ActionLink("Delete Tag", "Delete", new { id = Model.TagId })</p>

ToDoList/Views/Tags/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Tag

<h2>Edit</h2>

<h4>Edit this tag: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TagId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Tags/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models;

<h1>Tags</h1>

@if (@Model.Count == 0)
{
  <h3>No tags have been added yet!</h3>
} 

@foreach (Tag tag in Model)
{
  <li>@Html.ActionLink($"{tag.Title}", "Details", new { id = tag.TagId })</li>
}

<p>@Html.ActionLink("Add new tag", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>